game: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest #self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: run tests
      run: bash run_tests.sh
